apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
        role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: nfs-pvc
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
      volumes:
        - name: nfs-pvc
          gcePersistentDisk:
            pdName: disk-1
            fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
    name: nfs-server
spec:
    ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
    selector:
        role: nfs-server
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: nfs
    labels:
      service: mynfs
spec:
    capacity:
        storage: 100Gi
    accessModes:
        - ReadWriteMany
    nfs:
        server: nfs-server.default.svc.cluster.local
        path: "/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      service: mynfs
---
